### ISSUE TITLE
Registration as student #963

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#100]
https://github.com/ita-social-projects/SpaceToStudy-Client/issues/963
# [TC-ID] : Registration as student #963

### Priority
High

## Description

Verify that a Guest can register as a student with valid data

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is opened.
The user is not logged in on the website.

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. | Click "What can you do" link in the header |            | The page scrolled down to the title "Learn from experts", the button "Become a student" exists on the page |
| 2. | Click "Become a student" |            | A modal window with title "Sign up as a student" opened  |
| 3. | Open https://temp-mail.org/en/ in a new window |            | "Your Temporary Email Address" title is visible together with email address  |
| 4. | Copy temporary email |            |   |
| 5. | Return to a modal window with title "Sign up as a student"  |            | A modal window with title "Sign up as a student" is opened  |
| 6. | Enter data to the fields | First name = "John", Last name = "Doe", email - insert copied data from step 4, password = "1234qwer", confirm password = "1234qwer"  | The fields are filled in  | 
| 7. | Click checkbox "I agree to the Terms and Privacy Policy" |            | The box is checked   |
| 8. | Click "Sign up" button |            | New modal window opened with message to check email  |

**Comment by Natali-natali** [comment]
3, 4 і 5 крок мабуть лишні. Не варто писати про тимчасову пошту. Просто вказуєм яким даними заповнюємо поля.

А також в тайтл і дескрипшн вказати якими саме даними. Тобто Verify that a Guest can register as a student with valid data

**Comment by yprystai** [comment]
@Natali-natali , додав "with valid data". Щодо тимчасової пошти не згідний, бо потрібно якимось чином згенерувати унікальну пошту, яка раніше не використовувалася для реєстрації. Якщо вказати конкретні дані, то тест буде одноразовий.
