### ISSUE TITLE
Login as Student and fill in the information according to the stepers #964

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#101]
https://github.com/ita-social-projects/SpaceToStudy-Client/issues/964
# [TC-ID]: Login as a Student and fill in the information according to the stepper #964

### Priority
High

## Description

After first logging check if a student can see a stepper modal window and fill in the valid account information

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is open.
You are registered as a student
The email is verified
You have never logged in before

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. | Click the "Login" button in the header |            | Login modal window is opened |
| 2. | Fill in the proper credential and click "Login" |            | The "General" block of the stepper modal for filling in the new account info is opened|
| 3. | Fill the required fields and click "Next" |            | The "Interests" block of the stepper is opened |
| 4. | Choose a "Main tutoring category" and a "Subject" and click "Add one more Subject"|            | In the "Interests" block empty textboxes are available to choose a new "Main tutoring category" and a "Subject" |
| 5. |  In order to add one more subject, choose "Main tutoring category" and a "Subject" and click "Next" |            | The "Language" block of the stepper is opened |
| 6. | Choose a language in the "Your native language" list and click "Next" |            | The "Photo" block of the stepper is opened |
| 7. | Click "Upload your profile photo" |            | The window for choosing a photo from your current device is opened |
| 8. | Choose a photo (png, jpg, or jpeg, <= 10 Mb) from your device and click the appropriate button for adding |            | The photo is uploaded and you can see it on the "Photo preview" area in the "Photo" block of the stepper |
| 9. | Click "Finish" |            | Steper is closed, the Home page is opened, and the green Flash Notice "Success! Your data were added" appeared |

**Comment by Natali-natali** [comment]
Мені здається, що тайтл і дескріпшин варто змінити. "Згідно кроків" не дуже вірне формулювання, потрібно написати конкретно яку саме інформацію заповнити. 
Можливо такий варіант б підійшов
Filling in student information with valid data after confirming the email

**Comment by OlenkaMysko** [comment]
дякую, я тайтл лишала, як мануальщики створювали? можна, мабуть, змінити. А в дескріпшн тоді заміню "апропріейт" на "валід" - дякую

**Comment by OlenkaMysko** [comment]
а сам дескріпшн точний, бо це вікно вспливає саме після першого логіну, ти міг зареєструватися і верифікувати імейл значно скоріше і лиш тепер залогінитися - і отримаєш це вікно. Я це тестила. Тобто задача: перевірити чи появляється вікно і чи можливо його заповнити
