### ISSUE TITLE
Verify that the Guest is shown the tutor registration modal window after clicking the "Get started for free" button  #967

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#104]
#Verify that the Guest is shown the student registration modal window after clicking the "Get started for free" button 

### Priority
Priority Medium

## Description

Verify that the Guest is shown the student registration modal window after clicking the "Get started for free" button 

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is open.
The user is not logged in to the site

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. |Click on the “Get started for free” button on the main banner of the homepage.|            | The page scrolled down to the  "What can you do" block    |
| 2. | Click on the “Become a tutor” button |            |The "Sign up as a tutor" modal window is open  |

https://github.com/ita-social-projects/SpaceToStudy-Client/issues/967

**Comment by yprystai** [comment]
@Natali-natali мабуть, варто уточнити, що вважається критерієм для другого кроку"The "Register as a student" modal window is open", оскільки по факту відкривається вікно "Sign up as a student". Можливо Expected result має містити щось подібне до "New modal window with title 'Sign up as a student' is open"
