### ISSUE TITLE
Verify that a Guest can see the student registration 'How it works' block #974

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#105]
https://github.com/ita-social-projects/SpaceToStudy-Client/issues/974
# [TC-ID] : Verify that a Guest can see the student registration 'How it works' block #974

### Priority
Medium

## Description

Verify that a Guest can see the student registration 'How it works' block

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is opened.
The user is not logged in on the website.

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. | Click "How it works" link in the header |            | The page scrolled down to the title "How it works", the title "How it works" exists on the page |
| 2. | Verify that the switch under "How it works" title is switched to "Learn from Experts" |            | "Learn from Experts" option is black and "Share your Experience" is grey; "Select a Tutor", "Send Request", "Start Learning" titles exist on the page; "Become a student" button exists on the page  |

**Comment by Natali-natali** [comment]
Мені здається, що слово Verify в кроці 2 не зовсім підходить. Можливо краще написати click on checkbox або switch checkbox

**Comment by yprystai** [comment]
@Natali-natali справа в тому, що цей світчер якраз і не треба клікати, а треба пересвідчитися, що значення по замовчуванню "Learn from Experts". Я додав цей крок, бо зараз по замовчуванню "Learn from Experts", але не відомо як буде в майбутньому.
