### ISSUE TITLE
[Sign up as a tutor] Verify that the error message ‘Password cannot be shorter than 8 and longer than 25 characters’ is appeared after filling password field with invalid data in registration modal window #990

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#109]
# Verify that the error message ‘Password cannot be shorter than 8 and longer than 25 characters’ is appeared after filling  password field with invalid data in registration modal window 

### Priority
Priority High

## Description

[Sign up as a tutor] Verify that the error message ‘Password cannot be shorter than 8 and longer than 25 characters’ is appeared after filling  password field with invalid amount of characters in registration modal window

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is open.
The user is not logged in to the site

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. |Click on the “Get started for free” button on the main banner of the homepage.|            | The page scrolled down to the  "What can you do" block    |
| 2. | Click on the “Become a tutor” button |            |The Sign up as a tutor modal window is open  |
| 3. | Fill the First Name field  |TUTOR_FIRST_NAME     |The entered data is accepted, field is highlighted in gray |
| 4. | Fill the Last Name field | TUTOR_LAST_NAME        |The entered data is accepted, field is highlighted in gray |
| 5. | Fill the Email field  |TUTOR_EMAIL         |The entered data is accepted, field is highlighted in gray  |
| 6. | Fill the Password field with #Password | #Password: 1111111111111111111111111q  |The field is highlighted in red, the message "Password cannot be shorter than 8 and longer than 25 characters" is displayed  |

https://github.com/ita-social-projects/SpaceToStudy-Client/issues/990

**Comment by yprystai** [comment]
@Natali-natali другий крок Expected result - мабуть має бути "The Sign up as a tutor modal window is open"

**Comment by yprystai** [comment]
@Natali-natali щодо кроків 3-5
Думаю, доцільніше використовувати 
TUTOR_EMAIL
TUTOR_FIRST_NAME
TUTOR_LAST_NAME
