### ISSUE TITLE
[Sign up as a student] Verify that the error message ‘Password must contain at least one alphabetic and one numeric character’ is appeared after filling password field with invalid data in registration  modal window#989

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#110]
# Verify that the error message ‘Password must contain at least one alphabetic and one numeric character’ is appeared after filling  password field with invalid data in registration modal window

### Priority
Priority High

## Description

[Sign up as a tutor] Verify that the error message ‘Password must contain at least one alphabetic and one numeric character’ is appeared after filling  password field with invalid amount of characters in registration modal window

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is open.
The user is not logged in to the site

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. |Click on the “Get started for free” button on the main banner of the homepage.|            | The page scrolled down to the  "What can you do" block    |
| 2. | Click on the “Become a tutor” button |            |The Sign up as a tutor modal window is open  |
| 3. | Fill the First Name field with  | TUTOR_FIRST_NAME       |The entered data is accepted, field is highlighted in gray |
| 4. | Fill the Last Name field with  | TUTOR_LAST_NAME      |The entered data is accepted, field is highlighted in gray |
| 5. | Fill the Email field with | TUTOR_EMAIL        |The entered data is accepted, field is highlighted in gray  |
| 6. | Fill the Password field with #Password | #Password: %^&*()_+  |The field is highlighted in red, the message "Password must contain at least one alphabetic and one numeric character" is displayed  |

https://github.com/ita-social-projects/SpaceToStudy-Client/issues/989

**Comment by Anastasiia3795** [comment]
Мабуть, краще замінити свої дані в полях вводу на те, що кидав Любомир
