### ISSUE TITLE
[Login popup] Verify that Login button is unclickable without entering data in Email and Password fields #972

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#112]
# [TC-972] : Verify that the "Login" button is greyed out and unclickable without entered data to the "Email" and "Password" fields.

### Priority
Medium

## Description

Verify that the "Login" button is greyed out and unclickable without entered data to the required fields.

### Precondition

The site https://s2s-front-stage.azurewebsites.net/ is opened.

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. | Click on the "Login" button in the header on the right. |            | The login modal with title "Welcome back" is displayed. |
| 2. | Leave "Email" and "Password" fields empty and hover the mouse over the "Login" button in the form. |            | The cursor isn't changed its type and the "Login" button is remained greyed out (rgba(0, 0, 0, 0.12) and unclickable. |

https://github.com/ita-social-projects/SpaceToStudy-Client/issues/972

**Comment by yprystai** [comment]
@zakotiukk на мою думку, слід уточнити конкретно, що є результатом "The registration modal is displayed.". Наприклад, що з'явилося вікно з певним конкретним  текстом.
