### ISSUE TITLE
Verify that the registered user can access the personal cabinet

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#114]
https://github.com/ita-social-projects/SpaceToStudy-Client/issues/969

# [TC-ID] : Verify that the registered user (tutor) can access the personal cabinet

### Priority
Medium

## Description

Verify that the registered user can access the personal cabinet

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is accessible and open in a web browser.
The user is not logged in on the website.

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. | Click the "Sign in" button in the upper right corner of the header |            | The modal window with "Welcome back" title is open |
| 2. | Fill the "Email" field with valid data |    <TUTOR_EMAIL>       | The entered Email  is displayed in the "Email" field |
| 3. | Fill the "Password" field with valid data |     <TUTOR_PASSWORD>   | The masked password is displayed in the "Password" field |
| 4. | Сlick on the "Login" button |            | Authorized and redirected to the main page with "Popular Categories" section in the page content |
| 5. | Сlick on the "Account" button |            | Account drop-down list opens |
| 6. | Сlick on the "My profile" link |            | The personal account page with profile information is open |

**Comment by yprystai** [comment]
@Naccarato21 на мою думку, потрібно уточнити усі Expected result і вказати конкретні елементи, які підтверджують виконання кроку. Наприклад "The modal login is open" змінити на "The modal window with "Welcome back" title is open".

**Comment by Naccarato21** [comment]
done
