### ISSUE TITLE
[Sign up as a tutor popup] Verify that a Guest can log in as a Mentor clicking highlighted underlined text 'Log in' at the Tutor 'Sign Up' pop-up. #988

### ISSUE THREAD

**Issue by VolodumurBesarab** [UA-1023-TAQC/SpaceToStudyTA#127]
# [TC-ID] : [[Sign up as a tutor popup] Verify that a Guest can log in as a Mentor clicking highlighted underlined text 'Log in' at the Tutor 'Sign Up' pop-up. #988](https://github.com/UA-1023-TAQC/SpaceToStudyTA/issues/113)

### Precondition
The https://s2s-front-stage.azurewebsites.net/ site is opened.

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. | Switch from "Sign Up as Tutor" to "Share your Experience". |            | Button "Become a student" changed "Become a tutor" |
| 2. | The button "Become a Tutor" is clicked and "Sign Up" pop-up appeared.|            | Open modal window "Sign up as tutor" |
| 3. | Click the highlighted underlined text 'Log in' at the lowest row of Mentor 'Sign Up' pop-up. |            | 'Login" pop-up is opened |

**Comment by Anastasiia3795** [comment]
Може, сюди ще додати, що кнопка 'Become a tutor' знаходиться в розділі 'What can you do'?

**Comment by VolodumurBesarab** [comment]
done
