### ISSUE TITLE
Verify that the user cannot close the login modal by clicking outside of it.

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#97]
https://github.com/ita-social-projects/SpaceToStudy-Client/issues/973

# [TC-ID] : Verify that the user cannot close the login modal by clicking outside of it.

### Priority
Low

## Description

Verify that the user cannot close the login modal by clicking outside of it.

### Precondition

The website https://s2s-front-stage.azurewebsites.net/ is accessible and open in a web browser.
The user is not logged in on the website.

## Test Steps
| Step No.      | Step description       | Expected result   |
|-------------|:-------------|:-----|
| 1. | Click the "Login" button in the upper right corner of the header | The modal window with "Welcome back" title is open |
| 2. | Click outside the login modal | Nothing's happening. Login modal remained open |

**Comment by yprystai** [comment]
@Naccarato21 на мою думку, для кроку 1 Expected result потрібно уточнити, що є критерієм, що "modal login is open". Наприклад, що вікно має певний title тощо. Аналогічно для другого кроку.

**Comment by Naccarato21** [comment]
done
