### ISSUE TITLE
Offer details in student profile #1029

### ISSUE THREAD

**Issue by Natali-natali** [UA-1023-TAQC/SpaceToStudyTA#99]
https://github.com/ita-social-projects/SpaceToStudy-Client/issues/1029

# [TC-ID] : Check offer details contain appropriate data after creating request as a Student on the Category page #1029

### Priority
Medium

## Description

Verify that the data on the Offer details page matches the data entered by the Student after creating the request.

### Precondition

The website BASE_URL is open.
User is logged in as a Student.
Login credentials: email: STUDENT_EMAIL; password: STUDENT_PASSWORD

## Test Steps
| Step No.      | Step description       | Input data | Expected result   |
|-------------|:-------------|:-----------|:-----|
| 1. | Click on 'Categories' button |            | The Category page is opened. Page address change to https://s2s-front-stage.azurewebsites.net/categories |
| 2. | Click on 'Create request' button |            | The modal window named 'Create a New Request' is opened. |
| 3. | In modal window fill appropriate fields | Category: Music; Subject: Guitar; skill level: Beginner; Title: 'I'd like to become a guitar coach'; Describe your request: 'Prefer focus on standart'; Language: Ukrainian; value per lesson: 700 | The modal window named 'Create a New Request' is opened | Fields are filled with appropriate info successfully. |
| 4. | Click on 'Add to drafts' button |            | A pop up window is appeared. Page address chenge to https://s2s-front-stage.azurewebsites.net/offer-details/ Offer appeared under the block 'Offer details'. |
| 5. | Compare name of offer creator |            | Name of offer creator equals to 'Test T.' |
| 6. | Compare name of offer |            | Name of the offer equals to 'I'd like to become a guitar coach'  |
| 7. | Compare name of offer subject |            | Name of the offer subject equals to 'Guitar'  |
| 8. | Compare name of level |            | Name of level equals to 'Beginner'  |
| 9. | Compare name of language |            | Name of language equals to 'Ukrainian'  |
| 10. | Compare text of price |            | Text of price equals to '700'  |
| 11. | Compare text under 'About Offer' from 'About Offer' block |            | Text under 'About Offer' equals to 'Prefer focus on standart'  |
| 12. | Compare General Information (Tutoring subject) |            | Tutoring subject equals to 'Guitar'  |
| 13. | Compare General Information (Preparation levels) |            | Preparation levels equals to 'Beginner'  |
| 14. | Compare General Information (Tutoring language) |            | Tutoring language equals to 'Ukrainian'  |
| 15. | Compare General Information (Pricing) |            | Pricing equals to '700 UAH/hour'  |

**Comment by Anastasiia3795** [comment]
Created offer in status Draft exists until page is overloaded

**Comment by Natali-natali** [comment]
Я думаю що Description слід змінити на щось схоже до цього
Verify that the data on the Offer details page matches the data entered by the Student after creating the request.  

Також пріоритет мабуть вищий

**Comment by Natali-natali** [comment]
Я вчила, що кроки і результати ось так приблизно потрібно писати (на приклад крок 2)
Click "Create request" button
The  'Create a New Request' modal window  is opened. 
Обов'язково в теперішньому часі

Але можливо і такий варіант підійде як в тебе

**Comment by Anastasiia3795** [comment]
Виправила
